### ISSUE TITLE
Run CCL Script at time

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/alerts.neon#17]
Support setting an alarm or reminder that runs a CCL upon expiration.

- [ ] Intent match for "script alert", probably like "playable alerts" currently
- [ ] Extract valid script name from intent match (initially, require exact match like running a script does)
- [ ] Upon alert expiration, automatically dismiss (should not remain in active alerts once script starts)
- [ ] Run script as normally

Other considerations:
- We should fail gracefully if a script isn't available when an alert expires (maybe it was removed or renamed) and handle the alert as a spoken alert
- We should support running the alerts skill without the CC skill. For now, maybe just use the `self.neon_core` param for now to enable the "script alert" intent, later we can consider making CC skill required for alerts or a more specific check for that skill

**Comment by NeonAndrii** [comment]
Closed by #18
